disabled_rules:
  - operator_whitespace
  - nesting
  - multiple_closures_with_trailing_closure
excluded:
  - Carthage
  - Pods
  - fastlane
  - Clouds/GraphQL/API.swift
  - media
  - CloudsUITests
  - CloudsScreenshots
  - CloudsAPI/Sources/Generated
line_length: 200
type_name:
  min_length: 3
  max_length:
    warning: 50
    error: 60
