# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

desc 'Generate new localized screenshots'
lane :screenshots do
  capture_screenshots(scheme: 'CloudsScreenshots')
end

desc 'Runs UI tests'
lane :test_ui do
  set_info_plist_value(
    path: './Clouds/Info.plist',
    key: 'NSAppTransportSecurity', 
    subkey: 'NSAllowsLocalNetworking', 
    value: true, 
    output_file_name: './Clouds/Info.plist'
  )

  # Run the tests
  run_tests(
    project: 'Clouds.xcodeproj',
    scheme: 'CloudsUITests',
    device: 'iPhone 11 Pro',
    reinstall_app: true,
    clean: true,
    configuration: 'Debug',
    prelaunch_simulator: true,
  )
end

desc 'Lints Swift code'
lane :lint do
  swiftlint(
    mode: :lint,
    config_file: '.swiftlint.yml'
  )
end