name: SwiftLint

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
    paths:
      - ".github/workflows/swift_lint.yml"
      - ".swiftlint.yml"
      - "**/*.swift"

jobs:
  lint:
    name: SwiftLint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: SwiftLint
        uses: norio-nomura/action-swiftlint@3.1.0
