name: Xcode

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
    paths:
      - ".github/workflows/xcode.yml"
      - "Clouds/**"
      - "Clouds.xcodeproj/**"
      - Cartfile
      - Cartfile.resolved

jobs:
  build:
    name: Build
    runs-on: macOS-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Secrets
        shell: bash
        env:
          MAPBOX_SDK_PACKAGE_TOKEN: ${{ secrets.MAPBOX_SDK_PACKAGE_TOKEN }}
        run: echo -e "machine api.mapbox.com\n login mapbox\n password $MAPBOX_SDK_PACKAGE_TOKEN" > ~/.netrc

      - name: Select Xcode Version
        run: sudo xcode-select -switch /Applications/Xcode_13.0.app

      - name: Build App
        run: set -o pipefail && xcodebuild clean build -project Clouds.xcodeproj -scheme Clouds -configuration Debug CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO | xcpretty --simple
